bindings.menu = {
  'file:new'                  : 'n',
  'file:new-bottom'           : 'shift+n',
  'file:new-below'            : 'o',
  'file:new-above'            : 'shift+o',
  'file:focus-up'             : 'k',
  'file:focus-down'           : 'j',
  'file:focus-first'          : 'g g',
  'file:focus-last'           : 'shift+g',
  'file:focus-jump-up'        : 'ctrl+u',
  'file:focus-jump-down'      : 'ctrl+d',
  'file:jump'                 : 'mod+g',
  'file:reload'               : 'mod+r',
  'file:sort-file'            : 'mod+alt+\\',
  'file:archive'              : 'mod+\\',
  'file:reveal-in-finder'     : 'mod+r',
  'file:switch-directory'     : 'mod+o',

  'edit:undo'                 : 'mod+z',
  'edit:redo'                 : 'mod+shift+z',
  'edit:cut'                  : 'mod+x',
  'edit:copy'                 : 'mod+c',
  'edit:paste'                : 'mod+v',
  'edit:paste-before'         : 'mod+shift+v',
  'edit:delete'               : 'del',
  'edit:duplicate'            : 'mod+shift+d',
  'edit:select-all'           : 'mod+a',
  'edit:update'               : 'enter',
  'edit:insert-start'         : 'i',
  'edit:insert-end'           : 'a',
  'edit:update-clear'         : 'shift+c',
  'edit:toggle-complete'      : 'space',
  'edit:remove-priority'      : '0',
  'edit:move-up'              : 'mod+shift+up',
  'edit:move-down'            : 'mod+shift+down',

  'edit:toggle-priority:a'    : '1',
  'edit:toggle-priority:b'    : '2',
  'edit:toggle-priority:c'    : '3',
  'edit:toggle-priority:d'    : '4',
  'edit:toggle-priority:e'    : '5',

  'view:find'                 : '/',
  'view:find-project'         : 'mod+p',
  'view:find-context'         : 'mod+t',
  'view:sort-manually'        : 'mod+alt+,',
  'view:sort-priority'        : 'mod+alt+.',
  'view:clear-search'         : 'mod+l',
  'view:clear-group'          : 'mod+alt+l',
  'view:clear-all'            : 'mod+shift+l',

  'view:show-priority:a'      : 'shift+1',
  'view:show-priority:b'      : 'shift+2',
  'view:show-priority:c'      : 'shift+3',
  'view:show-priority:d'      : 'shift+4',
  'view:show-priority:e'      : 'shift+5'
};
