bindings.menu = {
  'file:new'                  : 'n',
  'file:new-bottom'           : 'N',
  'file:new-below'            : 'o',
  'file:new-above'            : 'O',
  'file:focus-up'             : 'k',
  'file:focus-down'           : 'j',
  'file:focus-first'          : 'g g',
  'file:focus-last'           : 'G',
  'file:focus-jump-up'        : 'ctrl+u',
  'file:focus-jump-down'      : 'ctrl+d',
  'file:jump'                 : 'mod+g',
  'file:move-complete-bottom' : 'mod+`',
  'file:move-priority-top'    : 'mod+shift+`',
  'file:archive'              : 'mod+alt+`',
  'file:reveal-in-finder'     : 'mod+r',
  'file:switch-directory'     : 'mod+0',

  'edit:undo'                 : 'mod+z',
  'edit:redo'                 : 'mod+shift+z',
  'edit:cut'                  : 'mod+x',
  'edit:copy'                 : 'mod+c',
  'edit:paste'                : 'mod+v',
  'edit:paste-before'         : 'mod+V',
  'edit:delete'               : 'del',
  'edit:duplicate'            : 'mod+D',
  'edit:select-all'           : 'mod+a',
  'edit:update'               : 'enter',
  'edit:insert-start'         : 'i',
  'edit:insert-end'           : 'a',
  'edit:change-clear'         : 'C',
  'edit:toggle-complete'      : 'space',
  'edit:move-up'              : 'mod+shift+up',
  'edit:move-down'            : 'mod+shift+down',

  'edit:assign-priority:a' : '1',
  'edit:assign-priority:b' : '2',
  'edit:assign-priority:c' : '3',
  'edit:assign-priority:d' : '4',
  'edit:assign-priority:e' : '5',

};
